name: build

on:
  push:
    branches-ignore:
      - "release-please-*"
    tags-ignore:
      - "v*.*.*"
      - "v*.*"
      - "v*"

jobs:
  build:
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        target_os: ["linux", "darwin", "windows"]
        target_arch: ["amd64", "arm64"]
    runs-on: ubuntu-latest
    env:
      REMOTE_CACHE: "ghcr.io/${{ github.repository_owner }}/earthly-cache"
      EARTHLY_MAX_REMOTE_CACHE: true
      EARTHLY_PUSH: true
      EARTHLY_CI: true
    steps:
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Earthly
        uses: earthly/actions-setup@v1
      - name: +build ${{ matrix.target_os }}/${{ matrix.target_arch }}
        run: |
          export EARTHLY_REMOTE_CACHE="${{ env.REMOTE_CACHE }}:$(basename ${{ github.repository }})"
          earthly +build --TARGET_OS=${{ matrix.target_os }} --TARGET_ARCH=${{ matrix.target_arch }}

  lint:
    permissions:
      actions: write
      contents: write
      packages: write
    runs-on: ubuntu-latest
    env:
      REMOTE_CACHE: "ghcr.io/${{ github.repository_owner }}/earthly-cache"
      EARTHLY_MAX_REMOTE_CACHE: true
      EARTHLY_CI: true
      EARTHLY_PUSH: true
    steps:
#      - name: Login to ghcr.io
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ github.repository_owner }}
#          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: "-c ./.golangci-lint.yml"
          skip-pkg-cache: true


#      - name: Setup Earthly
#        uses: earthly/actions-setup@v1
#      - name: earthly +lint
#        run: |
#          export EARTHLY_REMOTE_CACHE="${{ env.REMOTE_CACHE }}:$(basename ${{ github.repository }})"
#          earthly -a +lint/lint-report.xml ./lint-report.xml
#      - name: Report
#        if: always()
#        uses: mikepenz/action-junit-report@v3
#        with:
#          report_paths: lint-report.xml
#          annotate_only: true
#          detailed_summary: true